function getRandomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function createRandomUsername() {
  const adjectives = [
    "curious",
    "angry",
    "happy",
    "sad",
    "funny",
    "lazy",
    "crazy",
    "silly",
    "brave",
    "shy",
    "energetic",
    "sleepy",
    "grumpy",
    "cheerful",
    "playful",
    "clumsy",
    "fearless",
    "gentle",
    "kind",
    "loyal",
    "proud",
    "quiet",
    "bold",
    "charming",
    "daring",
    "eager",
    "fierce",
    "giddy",
    "jolly",
    "mellow",
    "nervous",
    "quirky",
    "sassy",
    "timid",
    "vivid",
    "zealous",
  ];

  const nouns = [
    "monkey",
    "donkey",
    "elephant",
    "tiger",
    "lion",
    "panda",
    "giraffe",
    "zebra",
    "kangaroo",
    "koala",
    "bear",
    "fox",
    "wolf",
    "rabbit",
    "squirrel",
    "otter",
    "beaver",
    "deer",
    "moose",
    "buffalo",
    "cheetah",
    "leopard",
    "jaguar",
    "hyena",
    "raccoon",
    "bat",
    "owl",
    "eagle",
    "hawk",
    "falcon",
    "parrot",
    "penguin",
    "flamingo",
    "peacock",
    "swan",
    "goose",
    "duck",
    "chicken",
    "rooster",
    "goat",
    "sheep",
    "cow",
    "horse",
    "pig",
    "dog",
    "cat",
  ];

  const adjective = getRandomElement(adjectives);
  const noun = getRandomElement(nouns);

  return `${adjective}_${noun}`;
}

export { createRandomUsername };
